config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "transactions#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/transaction.rb
class Transaction < ApplicationRecord
    enum :category, { debit: 'debit', credit: 'credit' }

    validates :data, comparison: { less_than_or_equal_to: proc { Date.current } }
    validates :description, presence: true
    validates :description, length: { maximum: 150 }
    validates :value, presence: true
    validates :category, presence: true

    validate :validate_if_exist_balance

    def self.current_balance
    self.credit.sum(:value) - self.debit.sum(:value)
    end

    private

    def validate_if_exist_balance
        return if credit?
        return if value.to_f <= Transaction.current_balance
        
        errors.add :value, "- You don't have enough balance"
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[ show update destroy ]

  # GET /transactions or /transactions.json
  def index
    @transactions = Transaction.order(data: :desc, created_at: :desc)

    @balance = Transaction.current_balance
  end

  # GET /transactions/1 or /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions or /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to transaction_url(@transaction), notice: "Transaction was successfully created." }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transaction_url(@transaction), notice: "Transaction was successfully updated." }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url, notice: "Transaction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.require(:transaction).permit(:data, :description, :value, :category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EvertinhoBank</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-lime-50">
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/transactions/_form.html.erb
<%= form_with(model: transaction, class: "contents") do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :data %>
    <%= form.date_field :data, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :category %>
    <%= form.select :category, [['Credit', 'credit'],['Debit', 'debit']], { }, {class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"} %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_field :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :value %>
    <%= form.number_field :value, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/transactions/_transaction.html.erb
<div id="<%= dom_id transaction %>" class="p-6 rounded-lg shadow-lg bg-white mb-4 flex <%= transaction.debit? ? 'font-bold text-red-700' : 'font-bold text-green-700' %>"> 
  <p class="my-5 flex-auto">
    <%= transaction.data %>
  </p>

  <p class="my-5 align-left flex-auto ">
    <%= transaction.description %>
  </p>

  <p class="my-5 text-left flex-auto">
    <%= number_to_currency transaction.value %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this transaction", transaction, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/transactions/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing transaction</h1>

  <%= render "form", transaction: @transaction %>

  <%= link_to "Show this transaction", @transaction, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to transactions", transactions_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/transactions/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="grid grid-cols-4 gap-4">

  <div class="p-6 rounded-lg shadow-lg bg-white mb-4">
    <%= image_tag 'evertinho-bank-white-test'%>
  </div>

  <div class="p-6 rounded-lg shadow-lg bg-white mb-4">
    <p class="font-bold">
      Balance
    </p>
    <p class="text-2xl">
      <%= number_to_currency @balance %>
    </p>
  </div>
  <div class="p-6 rounded-lg shadow-lg bg-white mb-4">
  <p class="font-bold">
    Transactions
  </p>
  <%= link_to 'New transaction', new_transaction_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %></div>
  
  <div class="p-6 rounded-lg shadow-lg bg-white mb-4">
    <p class="font-bold">
      Logout 
    </p>
  </div>
</div>

  <div id="transactions" class="min-w-full">
    <%= render @transactions %>
  </div>


</div>

app/views/transactions/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New transaction</h1>

  <%= render "form", transaction: @transaction %>

  <%= link_to 'Back to transactions', transactions_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/transactions/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @transaction %>

    <div class="inline-block ml-2">
      <%= button_to 'Destroy this transaction', transaction_path(@transaction), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to transactions', transactions_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>